### ISSUE TITLE
Problema con los Diales + y -

### ISSUE THREAD

**Issue by junsey** [Nullpo/Kallat-Tablero#1]
En teléfonos cuando la configuración de fuente esta puesta al minimo tamaño, los botones de - y + se ven afectado siendo casi imposibles de ver.

**Comment by Nullpo** [comment]
No se pudo reproducir el error. De todas formas le agregué unas cosas para que no modifique la fuente a usar (que se cague en la accesibilidad, basicamente).

Volver a abrir el bug si se puede reproducir! :)
