### ISSUE TITLE
Problema de Inicio Lento

### ISSUE THREAD

**Issue by junsey** [Nullpo/Kallat-Tablero#2]
Al entrar en la App demora al rededor de 1 segundo en reaccionar al usar los comandos, pero si la app se cierra y se abre nuevamente funciona normal.

"Demora hasta 1s en cambiar el número al apretar + o - (Moto G, primera generación, XT1034 ) a la segunda vez que se abre este problema desaparece…
"

**Comment by Nullpo** [comment]
Leyendo documentación, es un problema del evento "click" que tiene un delay. Lo cambié por onTouchStart y parece que va.

Me gustaría que se pruebe en el celular original. Reabrir el issue si no se solucionó!
